export {default as Hero} from "./hero/Hero"
export {default as Review} from "../components/review/Review"
export {default as Shop} from "../components/shop/Shop"
export {default as Info} from "../components/info/Info"
export {default as Trending} from "../components/trending/Trending"
export {default as Mission} from "../components/mission/Mission"
export {default as Magazine} from "../components/magazine/Magazine"
export {default as Product1} from "../components/bottle/Product1"
export {default as Cart} from "../components/cart/Cart" 
// export {default as Hero} from "../components/hero/Hero"
